Repository devfile/registry, pull requests merged in 2021-06, with the labels that each got.

#32 Fixed typo in nodejs stack devfile
  stacks/nodejs/devfile.yaml
Labels: lgtm, needs-ok-to-test

#33 Update sample icon link
  extraDevfileEntries.yaml
Labels: lgtm

#34 Move to use ubi11 image as no need for the big image anymore
  stacks/java-quarkus/devfile.yaml
Labels: lgtm

#37 Migrate devfile-registry acceptance tests
  .ci/acceptance-tests/devfile-registry-acceptance.yaml
Labels: lgtm

#38 Migrate openshift template for registry
  .ci/deploy/devfile-registry.yaml
Labels: lgtm

#36 Update Node.js DevFile to match brand guidelines
  stacks/nodejs/devfile.yaml
Labels: lgtm, ok-to-test

#39 Add Java/Maven tags to java-openliberty
  stacks/java-openliberty/devfile.yaml
Labels: lgtm, ok-to-test

#35 sample: point to new Node.js DevFile sample
  extraDevfileEntries.yaml
Labels: lgtm, ok-to-test

#40 Updating WildFly to 24.0.0.Final
  stacks/java-wildfly-bootable-jar/devfile.yaml
  stacks/java-wildfly/devfile.yaml
Labels: ok-to-test

#42 Update dockerfile to use yq
  .ci/Dockerfile
Labels: lgtm

#43 Disable layer caching on image build for registry
  .ci/build.sh
Labels: lgtm
