Repository devfile/registry, pull requests merged in 2021-11, with the labels that each got.

#80 Add viewer host alias
  .ci/deploy/devfile-registry.yaml
  stacks/nodejs-angular/devfile.yaml
  stacks/nodejs-nextjs/devfile.yaml
  stacks/nodejs-nuxtjs/devfile.yaml
  stacks/nodejs-react/devfile.yaml
  stacks/nodejs-svelte/devfile.yaml
  stacks/nodejs-vue/devfile.yaml
  tests/test.sh
Labels: lgtm

#81 Fix openshift template
  .ci/deploy/devfile-registry.yaml
Labels: lgtm

#79 dotnet: fix build failing due to running application.
  stacks/dotnet50/devfile.yaml
  stacks/dotnetcore31/devfile.yaml
Labels: lgtm, ok-to-test

#82 Add dotnet60 stack
  stacks/dotnet60/devfile.yaml
Labels: ok-to-test

#83 Enable viewer telemetry
  .ci/deploy/devfile-registry.yaml
Labels: lgtm

#84 add provider information in samples index
  extraDevfileEntries.yaml
Labels: lgtm
