Repository devfile/registry, pull requests merged in 2022-10, with the labels that each got.

#131 increase timeout in check_non_terminating tests and update image in java-quarkus to java 17
  stacks/java-quarkus/devfile.yaml
  tests/check_non_terminating.sh
Labels: lgtm, approved

#116 Update WebSphere Liberty logos
  stacks/java-websphereliberty-gradle/devfile.yaml
  stacks/java-websphereliberty/devfile.yaml
Labels: lgtm, ok-to-test, approved

#130 Changed the starterProjects name to appropriate ones.
  stacks/dotnet50/devfile.yaml
  stacks/dotnet60/devfile.yaml
  stacks/dotnetcore31/devfile.yaml
Labels: lgtm, ok-to-test, approved

#134 Updated the devfile metadata to be more consistent
  .editorconfig
  .gitattributes
  .github/workflows/check-architectures.yaml
  .github/workflows/ci.yaml
  .github/workflows/comment-pr.yaml
  .github/workflows/pushimge-next.yaml
  .github/workflows/trigger-redeploy.yaml
  .github/workflows/validate-devfiles.yaml
  CONTRIBUTING.md
  extraDevfileEntries.yaml
  stacks/dotnet50/devfile.yaml
  stacks/dotnet60/devfile.yaml
  stacks/dotnetcore31/devfile.yaml
  stacks/go/devfile.yaml
  stacks/java-maven/devfile.yaml
  stacks/java-openliberty-gradle/devfile.yaml
  stacks/java-openliberty/devfile.yaml
  stacks/java-quarkus/devfile.yaml
  stacks/java-springboot/devfile.yaml
  stacks/java-vertx/devfile.yaml
  stacks/java-websphereliberty-gradle/devfile.yaml
  stacks/java-websphereliberty/devfile.yaml
  stacks/java-wildfly-bootable-jar/devfile.yaml
  stacks/java-wildfly/devfile.yaml
  stacks/nodejs-angular/devfile.yaml
  stacks/nodejs-nextjs/devfile.yaml
  stacks/nodejs-nuxtjs/devfile.yaml
  stacks/nodejs-react/devfile.yaml
  stacks/nodejs-svelte/devfile.yaml
  stacks/nodejs-vue/devfile.yaml
  stacks/nodejs/devfile.yaml
  stacks/python/devfile.yaml
  tests/check_odov3.sh
Labels: lgtm

#137 Reverts dotnet stack projectTypes to dotnet
  extraDevfileEntries.yaml
  stacks/dotnet50/devfile.yaml
  stacks/dotnet60/devfile.yaml
  stacks/dotnetcore31/devfile.yaml
  stacks/java-springboot/devfile.yaml
Labels: lgtm, approved

#138 odo v3 tests: add `odo dev` failure detection
  tests/odov3/odo_test.go
Labels: lgtm

#140 Remove telemetry from staging server
  .ci/deploy/devfile-registry.yaml
Labels: lgtm, approved
