Repository devfile/registry, pull requests merged in 2022-05, with the labels that each got.

#103 Add default stack and tools review owners
  OWNERS
  stacks/OWNERS
  stacks/dotnet50/OWNERS
  stacks/dotnet60/OWNERS
  stacks/dotnetcore31/OWNERS
  stacks/go/OWNERS
  stacks/java-maven/OWNERS
  stacks/java-openliberty-gradle/OWNERS
  stacks/java-openliberty/OWNERS
  stacks/java-quarkus/OWNERS
  stacks/java-springboot/OWNERS
  stacks/java-vertx/OWNERS
  stacks/java-websphereliberty-gradle/OWNERS
  stacks/java-websphereliberty/OWNERS
  stacks/java-wildfly-bootable-jar/OWNERS
  stacks/java-wildfly/OWNERS
  stacks/nodejs-angular/OWNERS
  stacks/nodejs-nextjs/OWNERS
  stacks/nodejs-nuxtjs/OWNERS
  stacks/nodejs-react/OWNERS
  stacks/nodejs-svelte/OWNERS
  stacks/nodejs-vue/OWNERS
  stacks/nodejs/OWNERS
  stacks/php-laravel/OWNERS
  stacks/python-django/OWNERS
  stacks/python/OWNERS
Labels: lgtm

#109 Update the schema version to 2.1.0
  stacks/go/devfile.yaml
  stacks/java-maven/devfile.yaml
  stacks/java-quarkus/devfile.yaml
  stacks/java-springboot/devfile.yaml
  stacks/java-vertx/devfile.yaml
  stacks/java-wildfly-bootable-jar/devfile.yaml
  stacks/java-wildfly/devfile.yaml
  stacks/nodejs/devfile.yaml
  stacks/php-laravel/devfile.yaml
  stacks/python-django/devfile.yaml
  stacks/python/devfile.yaml
Labels: lgtm, ok-to-test

#111 Add service account for acceptance tests
  .ci/acceptance-tests/devfile-registry-acceptance.yaml
Labels: lgtm, approved
