Repository devfile/registry, pull requests merged in 2022-12, with the labels that each got.

#150 Updated go image to go-toolset
  stacks/go/devfile.yaml
Labels: lgtm, approved

#151 Changed GOPATH to fix permissions
  stacks/go/devfile.yaml
Labels: lgtm, approved

#152 Add securityContexts for OCP 4.12
  .ci/deploy/devfile-registry.yaml
  .ci/openshift_integration.sh
Labels: approved

#153 Updated composer image
  stacks/php-laravel/devfile.yaml
  stacks/python/3.0.0/docker/Dockerfile
Labels: lgtm

#149 Update build and deploy pipeline
  .ci/Dockerfile
  .ci/build_and_deploy.sh
  .ci/deploy/devfile-registry.yaml
  .ci/openshift_integration.sh
  .gitignore
Labels: lgtm, approved
