Repository devfile/registry, pull requests merged in 2022-11, with the labels that each got.

#142 Update anglular tags
  stacks/nodejs-angular/devfile.yaml
Labels: lgtm

#122 Declare missing debug endpoints
  stacks/java-maven/devfile.yaml
  stacks/java-openliberty-gradle/devfile.yaml
  stacks/java-openliberty/devfile.yaml
  stacks/java-quarkus/devfile.yaml
  stacks/java-springboot/devfile.yaml
  stacks/java-vertx/devfile.yaml
  stacks/java-websphereliberty-gradle/devfile.yaml
  stacks/java-websphereliberty/devfile.yaml
  stacks/java-wildfly-bootable-jar/devfile.yaml
  stacks/java-wildfly/devfile.yaml
  stacks/nodejs/devfile.yaml
  stacks/python-django/devfile.yaml
  stacks/python/devfile.yaml
  tests/check_odov2.sh
  tests/odov3/odo_test.go
Labels: lgtm, ok-to-test

#144 Halt updates from `devfile-index-base`
  .ci/Dockerfile
Labels: lgtm

#135 Remove .NET version number from template.
  extraDevfileEntries.yaml
Labels: lgtm, ok-to-test, approved

#145 Fix registry status in README
  README.md
Labels: lgtm

#119 use more up-to-date images for java-maven and java-springboot
  stacks/java-maven/devfile.yaml
  stacks/java-springboot/devfile.yaml
Labels: approved

#121 Fix missing `DEBUG_PORT` environment variable in Node.JS stack
  stacks/nodejs/devfile.yaml
Labels: lgtm, ok-to-test, approved

#148 Use different base image for dockerfile
  .ci/Dockerfile
Labels: lgtm, approved
