Repository devfile/registry, pull requests merged in 2023-08, with the labels that each got.

#198 rhtap-tests: Remove `-` from namespace generation
  tests/rhtap/rhtap_test.go
Labels: lgtm, ok-to-test, approved

#200 Generate namespace for every devfile samples in RHTAP cluster
  tests/check_rhtap_nightly.sh
  tests/rhtap/rhtap_test.go
Labels: lgtm, needs-ok-to-test, approved

#197 add dockerfile to support offline registry builds
  .ci/Dockerfile.offline
  .ci/build.sh
Labels: approved

#201 Update github actions to use NodeJS 16
  .github/workflows/check-architectures.yaml
  .github/workflows/ci.yaml
  .github/workflows/comment-pr.yaml
  .github/workflows/pushimge-next.yaml
  .github/workflows/trigger-redeploy.yaml
  .github/workflows/validate-stacks.yaml
Labels: lgtm, approved

#202 Update devfile.yaml
  stacks/java-wildfly/2.0.0/devfile.yaml
Labels: lgtm, approved
