Repository devfile/registry, pull requests merged in 2023-10, with the labels that each got.

#217 Upgrade timeout of deleted applications
  tests/rhtap/rhtap_test.go
Labels: lgtm, ok-to-test, approved

#218 Make sure to run `odo` v3 tests for stacks that have no starter projects
  .github/workflows/validate-stacks.yaml
  tests/odov3/odo_test.go
Labels: bug, lgtm, approved

#223 Extend gitSignOff
  renovate.json
Labels: lgtm, approved

#227 Assign a rhtap namespace for every devfile to avoid ArgoCD when delete applications
  .gitignore
  tests/rhtap/rhtap_test.go
Labels: lgtm, ok-to-test, approved

#228 [rhtap-e2e]: Remove components and application from test namespace
  tests/rhtap/rhtap_test.go
Labels: lgtm, ok-to-test, approved

#229 Do not remove namespace for debug utilities
  tests/rhtap/rhtap_test.go
Labels: lgtm, ok-to-test, approved

#230 Copy additional stack resources inside tmpDir before validating stacks with odov3
  tests/odov3/odo_test.go
  tests/odov3/types.go
Labels: lgtm, approved

#169 [java-springboot] Use LTS JDK 17 image
  stacks/java-springboot/1.3.0/devfile.yaml
  stacks/java-springboot/2.1.0/devfile.yaml
  stacks/java-springboot/2.1.0/docker/Dockerfile
  stacks/java-springboot/2.1.0/kubernetes/deploy.yaml
  stacks/java-springboot/stack.yaml
Labels: lgtm, ok-to-test, approved

#167 [java-maven] Use LTS JDK 17 image
  stacks/java-maven/1.2.0/devfile.yaml
  stacks/java-maven/1.3.0/devfile.yaml
  stacks/java-maven/stack.yaml
Labels: lgtm, ok-to-test, approved

#231 Increase java-quarkus container memory limit
  stacks/java-quarkus/devfile.yaml
Labels: lgtm, approved
