Repository devfile/registry, pull requests merged in 2024-07, with the labels that each got.

#440 Use same case for Java language in Wildfly stacks than others
  stacks/java-wildfly/2.0.0/devfile.yaml
  stacks/java-wildfly/2.0.1/devfile.yaml
  stacks/java-wildfly/2.0.2/devfile.yaml
Labels: lgtm, ok-to-test, approved

#444 Fix lastModified Filter
  .ci/generate_last_mod_file.sh
Labels: lgtm, approved

#438 Fix description for Java SpringBoot stack when using JDK 17 and not JDK 11
  stacks/java-springboot/1.3.0/devfile.yaml
  stacks/java-springboot/1.4.0/devfile.yaml
  stacks/java-springboot/2.1.0/devfile.yaml
  stacks/java-springboot/2.2.0/devfile.yaml
Labels: lgtm, ok-to-test, approved

#431 Replace starter projects from `odo-devfile` org
  stacks/java-maven/1.3.0/devfile.yaml
  stacks/java-maven/1.3.1/devfile.yaml
  stacks/java-springboot/1.2.0/devfile.yaml
  stacks/java-springboot/1.3.0/devfile.yaml
  stacks/java-springboot/1.4.0/devfile.yaml
  stacks/java-springboot/2.0.0/devfile.yaml
  stacks/java-springboot/2.1.0/devfile.yaml
  stacks/java-springboot/2.2.0/devfile.yaml
  stacks/nodejs/2.1.1/devfile.yaml
  stacks/nodejs/2.2.0/devfile.yaml
  stacks/nodejs/2.2.1/devfile.yaml
Labels: lgtm, approved

#441 Fix Maven version in description of Java Maven stack
  stacks/java-maven/1.2.0/devfile.yaml
  stacks/java-maven/1.3.0/devfile.yaml
  stacks/java-maven/1.3.1/devfile.yaml
Labels: lgtm, ok-to-test

#442 Remove LogManager property in Quarkus stacks (#1612)
  stacks/java-quarkus/1.3.0/devfile.yaml
  stacks/java-quarkus/1.3.1/devfile.yaml
  stacks/java-quarkus/1.4.0/devfile.yaml
  stacks/java-quarkus/1.4.1/devfile.yaml
  stacks/java-quarkus/1.5.0/devfile.yaml
Labels: lgtm

#439 Use latest Java Spring Boot stack as default
  stacks/java-springboot/stack.yaml
Labels: lgtm, ok-to-test, approved

#452 Added dotnet80 stack
  .github/CODEOWNERS
  stacks/dotnet80/devfile.yaml
Labels: lgtm, ok-to-test, approved

#460 Update generation script to handle non-versioned items
  .ci/generate_last_mod_file.sh
Labels: lgtm, approved
