Repository devfile/registry, pull requests merged in 2024-06, with the labels that each got.

#399 Use maven wrapper script instead of the mvn in java-quarkus commands
  stacks/java-quarkus/1.3.1/devfile.yaml
  stacks/java-quarkus/1.4.1/devfile.yaml
Labels: lgtm, ok-to-test, approved

#414 Multi Arch Image Building for Devfile Index
  .ci/Dockerfile
  .ci/Dockerfile.offline
  .ci/build-multi-arch.sh
  .ci/build.sh
  .github/workflows/ci.yaml
  .github/workflows/pushimge-next.yaml
  README.md
Labels: lgtm, approved, do-not-merge/hold

#412 Update `Maven Java` stack
  stacks/java-maven/1.3.1/devfile.yaml
  stacks/java-maven/stack.yaml
Labels: lgtm, ok-to-test

#421 Update contributing guide
  CONTRIBUTING.md
  DCO
  README.md
Labels: lgtm, approved

#420 Upgrade devfile registry testing modules & CI to Go 1.21
  .ci/Dockerfile
  .ci/Dockerfile.offline
  .ci/openshift_integration.sh
  .devfile.yaml
  .github/workflows/ci.yaml
  .github/workflows/devfile-ci.yaml
  .github/workflows/pushimge-next.yaml
  .github/workflows/validate-samples.yaml
  .github/workflows/validate-stacks.yaml
  README.md
  tests/README.md
  tests/odov3/go.mod
  tests/odov3/go.sum
  tests/odov3/odo_test.go
  tests/validate_devfile_schemas/go.mod
  tests/validate_devfile_schemas/go.sum
  tests/validate_devfile_schemas/validate_devfile_schemas_test.go
Labels: lgtm, approved

#422 Exclude Java vert.x 1.4.0 from odo3 check
  tests/check_odov3.sh
Labels: lgtm, approved

#429 Add new script for generating the last modified dates of stacks and samples
  .ci/Dockerfile
  .ci/Dockerfile.offline
  .ci/generate_last_mod_file.sh
Labels: lgtm, approved
