Repository devfile/registry, pull requests merged in 2024-05, with the labels that each got.

#374 Add new version and set https endpoint to nodejs-vue
  stacks/nodejs-vue/1.2.1/devfile.yaml
  stacks/nodejs-vue/stack.yaml
Labels: ok-to-test, approved

#385 Update OWNERS (remove myself)
  stacks/OWNERS
Labels: lgtm, approved

#387 Adding Ollama devfile
  stacks/ollama/OWNERS
  stacks/ollama/devfile.yaml
Labels: lgtm, approved

#395 chore: Update ollama OWNERS (adding 'manhah')
  stacks/ollama/OWNERS
Labels: lgtm, do-not-merge/invalid-owners-file, approved

#373 Add new version and set https endpoint to java-vertx
  stacks/java-vertx/1.4.0/devfile.yaml
  stacks/java-vertx/stack.yaml
Labels: lgtm, ok-to-test, approved

#384 Update the registry stack PR review process
  .github/CODEOWNERS
  CONTRIBUTING.md
  stacks/OWNERS
  stacks/dotnet50/OWNERS
  stacks/dotnet60/OWNERS
  stacks/dotnetcore31/OWNERS
  stacks/java-maven/OWNERS
  stacks/java-openliberty-gradle/OWNERS
  stacks/java-openliberty/OWNERS
  stacks/java-quarkus/OWNERS
  stacks/java-springboot/OWNERS
  stacks/java-vertx/OWNERS
  stacks/java-websphereliberty-gradle/OWNERS
  stacks/java-websphereliberty/OWNERS
  stacks/java-wildfly-bootable-jar/OWNERS
  stacks/java-wildfly/OWNERS
  stacks/nodejs/OWNERS
  stacks/ollama/OWNERS
  stacks/udi/OWNERS
Labels: lgtm, approved

#396 Bump up devfile library on dependent registry test modules
  tests/odov3/go.mod
  tests/odov3/go.sum
  tests/odov3/odo_test.go
  tests/validate_devfile_schemas/go.mod
  tests/validate_devfile_schemas/go.sum
Labels: lgtm, approved

#386 Adding go 1.21 devfile
  stacks/go/2.4.0/devfile.yaml
  stacks/go/2.4.0/docker/Dockerfile
  stacks/go/2.4.0/kubernetes/deploy.yaml
  stacks/go/stack.yaml
Labels: lgtm, approved

#398 chore: use https protocol and update devfile scheme to 2.2.2 for dotnetcore31 and angular
  stacks/dotnetcore31/devfile.yaml
  stacks/nodejs-angular/2.2.1/devfile.yaml
  stacks/nodejs-angular/stack.yaml
Labels: lgtm

#411 Remove konflux nightly run files
  tests/check_konflux_nightly.sh
  tests/konflux/go.mod
  tests/konflux/go.sum
  tests/konflux/konflux_test.go
  tests/konflux/types.go
Labels: lgtm, approved

#413 Fix samples path in workflow
  .github/workflows/validate-samples.yaml
  tests/README.md
Labels: lgtm, approved
