Repository devfile/registry, pull requests merged in 2024-02, with the labels that each got.

#284 Fix devfile udi stack icon
  stacks/udi/devfile.yaml
Labels: lgtm, approved

#280 Add vertx-configmap-example to odo3 check's skipped starterprojects
  tests/check_odov3.sh
Labels: lgtm, approved

#295 Add devfile for the Vert.x Java Stack with runtime ubi8/openjdk-11 image
  stacks/java-vertx/1.2.0/devfile.yaml
  stacks/java-vertx/1.3.0/devfile.yaml
  stacks/java-vertx/stack.yaml
  tests/check_odov3.sh
Labels: lgtm, ok-to-test, approved

#208 add lifecycle doc
  CONTRIBUTING.md
  LIFECYCLE.md
Labels: approved

#297 bump up e2e-tests to latest
  tests/rhtap/go.mod
  tests/rhtap/go.sum
Labels: lgtm, approved

#306 Add support for arm64 users to build scripts
  .ci/build_and_deploy.sh
  README.md
Labels: lgtm, approved

#307 [DevTools] Add codeowners to devfile owned stacks
  .github/CODEOWNERS
Labels: lgtm, approved
