Repository devfile/registry, pull requests merged in 2024-04, with the labels that each got.

#356 TEMP ignore schemaVersions 2.2.2 and 2.2.1 due to odo incompatibility
  tests/odov3/odo_test.go
  tests/odov3/types.go
Labels: lgtm, approved

#349 Update php-laravel devfile
  stacks/php-laravel/2.0.1/devfile.yaml
  stacks/php-laravel/stack.yaml
Labels: ok-to-test, approved

#347 Update nodejs-nextjs stack
  stacks/nodejs-nextjs/1.2.1/devfile.yaml
  stacks/nodejs-nextjs/stack.yaml
Labels: lgtm, ok-to-test, approved

#346 Update nodejs-nuxtjs stack
  stacks/nodejs-nuxtjs/1.2.1/devfile.yaml
  stacks/nodejs-nuxtjs/stack.yaml
Labels: lgtm, ok-to-test

#341 Fix java-quarkus devfile
  stacks/java-quarkus/1.3.0/devfile.yaml
  stacks/java-quarkus/1.4.0/devfile.yaml
  stacks/java-quarkus/stack.yaml
Labels: lgtm, ok-to-test, approved

#358 Add a 2.2.2 devfile version and set https endpoint to Python stack
  stacks/python/2.2.0/devfile.yaml
  stacks/python/3.1.0/devfile.yaml
  stacks/python/3.1.0/docker/Dockerfile
  stacks/python/3.1.0/kubernetes/deploy.yaml
  stacks/python/stack.yaml
Labels: lgtm, ok-to-test, approved

#365 Fix Nightly Run Failures
  .github/workflows/validate-stacks.yaml
  tests/check_odov2.sh
  tests/check_odov3.sh
  tests/odov3/odo_test.go
Labels: lgtm, approved

#345 Update default version for java-wildfly-bootable-jar stack; set https protocol
  stacks/java-wildfly-bootable-jar/1.3.0/devfile.yaml
  stacks/java-wildfly-bootable-jar/stack.yaml
Labels: lgtm, ok-to-test, approved

#357 chore: Update go devfile
  stacks/go/1.2.1/devfile.yaml
  stacks/go/1.3.1/devfile.yaml
  stacks/go/stack.yaml
Labels: lgtm, ok-to-test, approved

#368 Fixing small issues in WildFly 2.0.1
  stacks/java-wildfly/2.0.2/devfile.yaml
  stacks/java-wildfly/stack.yaml
Labels: lgtm, approved

#351 Update java-openliberty devfile
  stacks/java-openliberty/devfile.yaml
Labels: lgtm, ok-to-test, approved, do-not-merge/hold

#350 Update java-openliberty-gradle devfile
  stacks/java-openliberty-gradle/devfile.yaml
Labels: lgtm, ok-to-test, do-not-merge/hold

#344 Update stacks/java-websphereliberty-gradle/devfile.yaml
  stacks/java-websphereliberty-gradle/devfile.yaml
Labels: lgtm, ok-to-test, approved, do-not-merge/hold

#343 Update stacks/java-websphereliberty/devfile.yaml
  stacks/java-websphereliberty/devfile.yaml
Labels: lgtm, ok-to-test, approved, do-not-merge/hold

#367 Add a 2.2.2 devfile version and set https endpoint to Spring Boot stack
  stacks/java-springboot/1.4.0/devfile.yaml
  stacks/java-springboot/2.2.0/devfile.yaml
  stacks/java-springboot/2.2.0/docker/Dockerfile
  stacks/java-springboot/2.2.0/kubernetes/deploy.yaml
  stacks/java-springboot/stack.yaml
Labels: lgtm, ok-to-test, do-not-merge/hold

#369 Update Nightly Run
  tests/check_odov2.sh
  tests/check_odov3.sh
Labels: lgtm, approved

#372 Use odo nightly builds instead of 3.15.0
  .github/workflows/validate-stacks.yaml
Labels: lgtm, approved
